
services:
  immich-server:
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    env_file:
      - .env
    volumes:
      - ${IMMICH_UPLOAD_LOCATION}:/data
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - redis
      - database
    ports:
      - "2283:2283"
    networks:
      - proxy
    labels:
      - tsdproxy.enable=true
      - tsdproxy.name=immich
      - tsdproxy.port=2283
    restart: always

  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    restart: always
    networks:
      - proxy

  redis:
    image: docker.io/valkey/valkey:9@sha256:fb8d272e529ea567b9bf1302245796f21a2672b8368ca3fcb938ac334e613c8f
    restart: always
    networks:
      - proxy

  database:
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:bcf63357191b76a916ae5eb93464d65c07511da41e3bf7a8416db519b40b1c23
    environment:
      POSTGRES_PASSWORD: ${IMMICH_DB_PASSWORD}
      POSTGRES_USER: ${IMMICH_DB_USERNAME}
      POSTGRES_DB: ${IMMICH_DB_DATABASE_NAME}
    volumes:
      - ${IMMICH_DB_DATA_LOCATION}:/var/lib/postgresql/data
    restart: always
    networks:
      - proxy

volumes:
  model-cache:

networks:
  proxy:
    external: true
