
services:
  playit:
    image: ghcr.io/playit-cloud/playit-agent:0.16
    network_mode: host
    env_file:
      - .env
    environment:
      - SECRET_KEY=${MINECRAFT_SECRET_KEY}

  minecraft:
    image: itzg/minecraft-server:latest
    ports:
      - "25565:25565"
    env_file:
      - .env
    environment:
      EULA: "TRUE"
      TYPE: PAPER
      VERSION: "1.21.10"
      MEMORY: 2G
      DIFFICULTY: easy
      MODE: survival
      PVP: "true"
      ONLINE_MODE: "true"
      VIEW_DISTANCE: 24
      SIMULATION_DISTANCE: 12
      ALLOW_FLIGHT: "false"
      MOTD: ${MINECRAFT_MOTD}
      USE_AIKAR_FLAGS: "true"
    volumes:
      - ./games/minecraft/world-data:/data
    restart: unless-stopped
