name: mc-filippa

services:
  playit:
    image: ghcr.io/playit-cloud/playit-agent:0.16
    network_mode: host
    env_file:
      - .env
    environment:
      - SECRET_KEY=${SECRET_KEY}

  minecraft:
    image: itzg/minecraft-server:latest
    container_name: minecraft
    ports:
      - "25565:25565"
    env_file:
      - .env
    environment:
      EULA: "TRUE"
      ENABLE_RCON: true

      # Server type
      TYPE: PAPER
      VERSION: "1.21.10"

      # Memory
      MEMORY: 2G

      # Gameplay
      DIFFICULTY: easy
      MODE: survival
      PVP: "true"
      ONLINE_MODE: "true"
      SEED: ${SEED}

      # Quality of life
      VIEW_DISTANCE: 24
      SIMULATION_DISTANCE: 12
      ALLOW_FLIGHT: "false"

      # Cosmetic
      MOTD: ${MOTD}

      # JVM optimizations (safe defaults)
      USE_AIKAR_FLAGS: "true"
    volumes:
      - ./minecraft-data:/data
    restart: unless-stopped

