# Reference: https://setupmc.com/java-server/

services:
  playit:
    image: ghcr.io/playit-cloud/playit-agent:0.16
    network_mode: host
    env_file:
      - .env
    environment:
      - SECRET_KEY=${SECRET_KEY}

  minecraft:
    image: itzg/minecraft-server:latest
    container_name: minecraft
    ports:
      - "25565:25565"
      - "24454:24454" # Required for Simple Voice Chat mod
    env_file:
      - .env
    environment:
      EULA: "TRUE"
      TYPE: "FABRIC"
      VERSION: "1.21.10"
      ENABLE_RCON: true

      # Memory
      MEMORY: 4G

      # Gameplay
      DIFFICULTY: easy
      MODE: survival
      PVP: "true"
      ONLINE_MODE: "true"
      SEED: ${SEED}

      # Quality of life
      VIEW_DISTANCE: 24
      SIMULATION_DISTANCE: 12
      ALLOW_FLIGHT: "false"
      MAX_PLAYERS: 10
      TZ: "Europe/Stockholm"

      # Cosmetic
      MOTD: ${MOTD}

      # JVM optimizations (safe defaults)
      USE_AIKAR_FLAGS: "true"

      # Mods
      MODRINTH_DOWNLOAD_DEPENDENCIES: "optional"
      MODRINTH_ALLOWED_VERSION_TYPE: "alpha"
      MODRINTH_PROJECTS: |-
        simple-voice-chat
        rei
        tabtps
        lithium
        ferrite-core
        krypton
        c2me-fabric
        scalablelux
        alternate-current
        chunky
        distanthorizons

    volumes:
      - ./minecraft-data:/data
    restart: unless-stopped

