
services:
  actual_server:
    image: docker.io/actualbudget/actual-server:latest
    container_name: actual_server
    environment:
      - TZ=${TZ}
    volumes:
      # Change './actual-data' below to the path to the folder you want Actual to store its data in on your server.
      # '/data' is the path Actual will look for its files in by default, so leave that as-is.
      - ./actual-data:/data
    healthcheck:
      test: ['CMD-SHELL', 'node src/scripts/health-check.js']
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 20s
    restart: unless-stopped
    ports:
      - "3000:3000"
    labels:
      - tsdproxy.enable=true
      - tsdproxy.name=actual
      - tsdproxy.port=3000
