
services:
  jellyfin:
    image: jellyfin/jellyfin
    # container_name removed
    env_file:
      - .env
    ports:
      - 8096:8096/tcp
      - 7359:7359/udp
    volumes:
      - jellyfin-config:/config
      - jellyfin-cache:/cache
      - type: bind
        source: ${JELLYFIN_SHOWS_DIR}
        target: /shows
      - type: bind
        source: ${JELLYFIN_MOVIES_DIR}
        target: /movies
      - type: bind
        source: ${JELLYFIN_MUSIC_DIR}
        target: /music
    restart: unless-stopped
    environment:
      - JELLYFIN_PublishedServerUrl=http://jellyfin.hydra-adelie.ts.net/
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    labels:
      - tsdproxy.enable=true
      - tsdproxy.name=jellyfin
      - tsdproxy.port=8096
    networks:
      - proxy

volumes:
  jellyfin-config:
  jellyfin-cache:

networks:
  proxy:
    external: true
