
services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    restart: unless-stopped
    environment:
      - TZ=${TZ}
    env_file:
      - .env
    volumes:
      - ./ha-config:/config
      - /etc/localtime:/etc/localtime:ro
    network_mode: host # Uncomment on Linux systems to use host networking
    # ports:
    #   - "8123:8123" # Comment out if using host networking
    privileged: true
    labels:
      - tsdproxy.enable=true
      - tsdproxy.name=homeassistant
      - tsdproxy.port=8123

